# Generated by Django 3.0 on 2021-05-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField(verbose_name='Координата Х')),
                ('y_coordinate', models.FloatField(verbose_name='Координата У')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC устройства')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC устройства')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.Subdivision', verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.TextField(blank=True, null=True, verbose_name='Трекинг')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Transport', verbose_name='Транспорт')),
            ],
        ),
    ]
