# Generated by Django 3.0 on 2021-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='last_coordinate_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Местонахождение по X'),
        ),
        migrations.AddField(
            model_name='transport',
            name='last_coordinate_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Местонахождение по Y'),
        ),
    ]
